name: 'build-docker-image'
description: 'Action for building docker image and pushing it to specified aws ecr repository'
author: 'patrik.beka@powerex.io'

inputs:
  docker-repo:
    required: true
    type: string
    description: "name of the docker repo in aws ecr where the image will be pushed"
  working-directory:
    required: true
    type: string
    description: "set this to working directory where the app with dockerfile is located"
  aws-access-key-id:
    required: true
    description: "set this to AWS_ACCESS_KEY_ID of your user"
  aws-secret-access-key:
    required: true
    description: "set this to AWS_SECRET_ACCESS_KEY of your user"
  aws-account-id:
    required: true
    description: "set this to AWS_ACCOUNT_ID of your user"

outputs:
  tag-to-deploy:
    description: "Published image tag for immediate deployment"
    value: ${{ steps.output-docker-tag.outputs.TAG_TO_DEPLOY }}

runs:
  using: "composite"

  steps:

    - name: Set docker tag
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/master' || ${{ github.ref }} == 'refs/heads/main' ]]; then
          # set tags as env vars in current runner
          echo "TAG=latest,prod_$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
        else
          # set tags as env vars in current runner
          echo "TAG=$(echo test-deploy_${{ github.head_ref || github.ref_name }} | tr -s '/' '_' | tr -s '#' '_' )" >> "$GITHUB_ENV"
        fi
      shell: bash

    - name: Docker build and push
      uses: kciter/aws-ecr-action@master
      with:
        access_key_id: ${{ inputs.aws-access-key-id }}
        secret_access_key: ${{ inputs.aws-secret-access-key }}
        account_id: ${{ inputs.aws-account-id }}
        repo: ${{ inputs.docker-repo }}
        region: eu-central-1
        tags: ${{ env.TAG }}
        dockerfile: "${{ inputs.working-directory }}/Dockerfile"
        create_repo: false
        set_repo_policy: false
        repo_policy_file: repo-policy.json
        path: ${{ inputs.working-directory }}

    # can`t do this in step 'Set docker tag' because for some reason env.TAG is empty - probably is filled after the step is finished
    - name: Show published docker image tag and set it as output of job
      id: output-docker-tag
      run: |
        echo "following tags for docker image: ${{ env.TAG }} were pushed"

        # set output tag from job, going for real tag 'test_deploy_*', or 'prod_*' not 'latest'
        echo "TAG_TO_DEPLOY=$( echo  ${{ env.TAG }} | cut -d ',' -f 2)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Create summary
      run: |
        # create job summary
        echo "### \#\# pushed tags: '${{ env.TAG }}' to aws ecr registry" >> $GITHUB_STEP_SUMMARY
        echo "### \#\# " >> $GITHUB_STEP_SUMMARY
        echo "### \#\# going to use following tag: '${{ steps.output-docker-tag.outputs.TAG_TO_DEPLOY }}' for deployment" >> $GITHUB_STEP_SUMMARY
      shell: bash
