name: 'setup-renv'
description: 'Action to setup renv and install R dependencies in the lockfile'
author: 'patrik.beka@powerex.io'
inputs:
  working-dir:
    description: 'Working directory with source codes and renv.lock file'
    required: true
  renv-version:
    description: 'Version of renv package'
    required: false
    default: 0.14.0
  cache-version:
    description: 'Version of renv cache'
    required: false
    default: v3
runs:
  using: "composite"
  steps:
      - name: Check if lockfile exist
        run: |
          FILE=${{ inputs.working-dir }}/renv.lock
          if [ -f "$FILE" ]; then
              echo "$FILE found."
          else
              echo "$FILE does not exist."
              exit 1
          fi
        shell: bash

      - name: Install renv
        run: |
          if (require("remotes") == FALSE) {
            install.packages("remotes")
          }
          remotes::install_github("rstudio/renv@${{ inputs.renv-version }}", upgrade = "never")
        shell: Rscript {0}

      - name: Install dependencies from lockfile
        run: |
          # Just install packages - no caching
          Sys.setenv(RENV_CONFIG_REPOS_OVERRIDE = "https://packagemanager.posit.co/cran/__linux__/focal/latest")
          
          # Restore to both global and local
          renv::restore(project = "${{ inputs.working-dir }}", prompt = FALSE, library = "/usr/local/lib/R/site-library")
          
          # Activate and restore locally
          renv::activate(project = "${{ inputs.working-dir }}")
          renv::restore(project = "${{ inputs.working-dir }}", prompt = FALSE)
          
          # Isolate
          renv::isolate(project = "${{ inputs.working-dir }}")
        shell: Rscript {0}
