name: 'build-docker-image-arm64'
description: 'Action for building docker image and pushing it to specified aws ecr repository'
author: 'rasto.liska@powerex.io'

inputs:
  docker-repo:
    required: true
    type: string
    description: "name of the docker repo in aws ecr where the image will be pushed"
  working-directory:
    required: true
    type: string
    description: "set this to working directory where the app with dockerfile is located"
  aws-access-key-id:
    required: true
    description: "set this to AWS_ACCESS_KEY_ID of your user"
  aws-secret-access-key:
    required: true
    description: "set this to AWS_SECRET_ACCESS_KEY of your user"
  aws-account-id:
    required: true
    description: "set this to AWS_ACCOUNT_ID of your user"
  build-args:
    required: false
    type: string
    description: "Additional build arguments to pass to Docker"

outputs:
  tag-to-deploy:
    description: "Published image tag for immediate deployment"
    value: ${{ steps.output-docker-tag.outputs.TAG_TO_DEPLOY }}

runs:
  using: "composite"

  steps:

    - name: Set docker tag
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/master' || ${{ github.ref }} == 'refs/heads/main' ]]; then
          # set tags as env vars in current runner
          echo "TAG=latest,prod_$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
        else
          # set tags as env vars in current runner
          echo "TAG=$(echo test-deploy_${{ github.head_ref }} | tr -s '/' '_' | tr -s '#' '_' )" >> "$GITHUB_ENV"
        fi
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-central-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.working-directory }}
        file: ${{ inputs.working-directory }}/Dockerfile
        push: true
        platforms: linux/arm64
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.docker-repo }}:${{ env.TAG }}     
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ inputs.docker-repo }}-arm64
        cache-to: type=gha,mode=max,scope=${{ inputs.docker-repo }}-arm64

    # can`t do this in step 'Set docker tag' because for some reason env.TAG is empty - probably is filled after the step is finished
    - name: Show published docker image tag and set it as output of job
      id: output-docker-tag
      run: |
        echo "following tags for docker image: ${{ env.TAG }} were pushed"

        # set output tag from job, going for real tag 'test_deploy_*', or 'prod_*' not 'latest'
        echo "TAG_TO_DEPLOY=$( echo  ${{ env.TAG }} | cut -d ',' -f 2)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Create summary
      run: |
        # create job summary
        echo "### \#\# pushed tags: '${{ env.TAG }}' to aws ecr registry" >> $GITHUB_STEP_SUMMARY
        echo "### \#\# " >> $GITHUB_STEP_SUMMARY
        echo "### \#\# going to use following tag: '${{ steps.output-docker-tag.outputs.TAG_TO_DEPLOY }}' for deployment" >> $GITHUB_STEP_SUMMARY
      shell: bash
