on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
        description: "set this to AWS_ACCESS_KEY_ID of your user"
      aws-secret-access-key:
        required: true
        description: "set this to AWS_SECRET_ACCESS_KEY of your user"
      slack-webhook-url:
        required: true
        description: "Slack webhook URL for notifications"
    inputs:
      aws-region:
        required: true
        type: string
        description: "set this to your preferred AWS region, e.g. us-west-1"
      app:
        required: true
        type: string
        description: "set this to your app name - service/task definition name, e.g. emsi - for deploying multiple instances of app 'emsi', or specific 'emsi-stm-dubnica' - for deploying only 1 specific instance)"
      ecs-cluster:
        required: true
        type: string
        description: "set this to your Amazon ECS cluster name, e.g. ecs-dev"
      image:
        required: true
        type: string
        description: "image to deploy to ecs in task def, e.g. 587619238227.dkr.ecr.eu-central-1.amazonaws.com/imbalance-service"
      test-mode:
        required: false
        type: boolean
        description: "Enable test mode to skip actual deployment"
        default: true

jobs:
  list-instances:
    uses: PowereX-jsa/pwx-actions/.github/workflows/list-ecs-instances.yml@master
    secrets: 
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
    with:
      aws-region: ${{ inputs.aws-region }}
      app: ${{ inputs.app }}

  deploy:
    if: ${{ !inputs.test-mode }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list-instances.outputs.instances-matrix) }}
    needs: [ list-instances ]
    uses: PowereX-jsa/pwx-actions/.github/workflows/task-def-app-deploy.yml@master
    secrets:
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
    with:
      aws-region: ${{ inputs.aws-region }}
      ecs-service: ${{ matrix.instance }}
      ecs-task-definition: ${{ matrix.instance }}
      ecs-cluster: ${{ inputs.ecs-cluster }}
      image: ${{ inputs.image }}

  mock-deploy:
    if: ${{ inputs.test-mode }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list-instances.outputs.instances-matrix) }}    
    needs: [ list-instances ]
    runs-on: ubuntu-latest
    steps:
      - name: Mock deployment simulation
        run: |
          echo "🧪 TEST MODE: Simulating deployment..."
          echo "AWS Region: ${{ inputs.aws-region }}"
          echo "ECS Cluster: ${{ inputs.ecs-cluster }}"
          echo "ECS Service: ${{ matrix.instance }}"
          echo "Image: ${{ inputs.image }}"
          sleep 3
          exit 1 # Simulate failure for testing purposes
          echo "✅ Mock deployment completed successfully"

  notify-slack:
    # if: always()
    if: always() && (inputs.test-mode || contains(toJson(needs.mock-deploy.*.result), 'failure')) && contains(inputs.ecs-cluster, 'dev')
    needs: [deploy, mock-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: short_commit
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT        

      - name: Notify Slack
        uses: PowereX-jsa/pwx-actions/common-actions/notify-slack@1534-github-actions-slack
        with:
          slack-webhook-url: ${{ secrets.slack-webhook-url }}
          status: ${{ inputs.test-mode && 'success' || needs.mock-deploy.result }}
          repository: ${{ github.repository }}
          commit-url: ${{ format('{0}/{1}/commit/{2}', github.server_url, github.repository, github.sha) }}
          commit-slug: ${{ steps.short_commit.outputs.SHORT_SHA }}
          author: ${{ github.actor }}
          job: ${{ inputs.test-mode && 'Mock ECS Deployment' || 'ECS Deployment' }}
          event-name: ${{ github.event_name }}
          workflow: ${{ github.workflow }}
          run-id: ${{ github.run_id }}
          message: "${{ inputs.test-mode && '🧪 TEST: ' || '' }}ECS Deployment: ${{ inputs.app }} to ${{ inputs.ecs-cluster }}"
