on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
        description: "set this to AWS_ACCESS_KEY_ID of your user"
      aws-secret-access-key:
        required: true
        description: "set this to AWS_SECRET_ACCESS_KEY of your user"
    inputs:
      aws-region:
        required: true
        type: string
        description: "set this to your preferred AWS region, e.g. us-west-1"
      app:
        required: true
        type: string
        description: "set this to your app name - task definition name"
      ecs-cluster:
        required: true
        type: string
        description: "set this to your Amazon ECS cluster name, e.g. ecs-dev"
      image:
        required: true
        type: string
        description: "image to deploy to ecs in task def"

jobs:
  list-scheduled-tasks:
    runs-on: ubuntu-latest
    outputs:
      tasks-matrix: ${{ steps.get-tasks.outputs.matrix }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
          mask-aws-account-id: false

      - name: Get scheduled tasks
        id: get-tasks
        run: |
          echo "Listing EventBridge rules with prefix ${{ inputs.app }}..."
          
          # Try standard EventBridge rules first
          aws events list-rules --name-prefix "${{ inputs.app }}" --query "Rules[].Name" --output json | jq -c '.' > tasks.json
          
          # If no results, try EventBridge Scheduler
          if [ "$(cat tasks.json)" == "[]" ]; then
            echo "No EventBridge rules found, checking EventBridge Scheduler..."
            aws scheduler list-schedules --name-prefix "${{ inputs.app }}" --query "Schedules[].Name" --output json | jq -c '.' > tasks.json
          fi
          
          # If still no results, just try to update the task definition directly
          if [ "$(cat tasks.json)" == "[]" ]; then
            echo "No scheduled tasks found, will try to update task definition directly"
            echo "[\"${{ inputs.app }}\"]" > tasks.json
          fi
          
          jq -c '{"task": .}' tasks.json > matrix.json
          echo "matrix=$(cat matrix.json | tr -d '\n')" >> $GITHUB_OUTPUT
          
          echo "Generated matrix:"
          cat matrix.json

  deploy:
    needs: [list-scheduled-tasks]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list-scheduled-tasks.outputs.tasks-matrix) }}
    env:
      ACTIONS_STEP_DEBUG: true
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
          mask-aws-account-id: false

      - name: Get task information
        id: get-task-info
        run: |
          # List all available task definitions to debug
          echo "Available task definitions for prefix ${{ inputs.app }}:"
          aws ecs list-task-definitions --family-prefix "${{ inputs.app }}" --status ACTIVE
          
          # Check if this is an EventBridge rule
          if aws events describe-rule --name "${{ matrix.task }}" 2>/dev/null; then
            echo "This is an EventBridge rule"
            TASK_TYPE="rule"
            
            # Get the target and extract task definition ARN 
            aws events list-targets-by-rule --rule "${{ matrix.task }}" > rule-target.json
            echo "Target information:"
            cat rule-target.json
            
            ARN_PATH=$(jq -r '.Targets[0].EcsParameters.TaskDefinitionArn' rule-target.json)
            echo "Task definition ARN from rule: $ARN_PATH"
          
          # Check if this is an EventBridge schedule
          elif aws scheduler get-schedule --name "${{ matrix.task }}" 2>/dev/null; then
            echo "This is an EventBridge scheduler task"
            TASK_TYPE="schedule"
            
            # Get the schedule details and extract task definition ARN
            aws scheduler get-schedule --name "${{ matrix.task }}" > schedule.json
            echo "Schedule information:"
            cat schedule.json
            
            ARN_PATH=$(jq -r '.Target.EcsParameters.TaskDefinitionArn' schedule.json)
            echo "Task definition ARN from schedule: $ARN_PATH"
          
          else
            echo "This is a direct task definition"
            TASK_TYPE="taskdef"
            ARN_PATH=""
          fi
          
          # If we have an ARN, extract the task definition name
          if [ -n "$ARN_PATH" ] && [ "$ARN_PATH" != "null" ]; then
            echo "Extracting task definition name from ARN: $ARN_PATH"
            # The format is arn:aws:ecs:region:account:task-definition/name:revision
            TASK_DEF=$(echo "$ARN_PATH" | awk -F'/' '{print $2}' | awk -F':' '{print $1}')
            echo "Extracted task definition name: $TASK_DEF"
          else
            echo "No task definition ARN found, using app name"
            TASK_DEF="${{ inputs.app }}"
          fi
          
          echo "task_type=$TASK_TYPE" >> $GITHUB_OUTPUT
          echo "task_def=$TASK_DEF" >> $GITHUB_OUTPUT
          echo "Using task definition: $TASK_DEF with type $TASK_TYPE"
          
          # List specific task definition detail to verify it exists
          echo "Verifying task definition exists:"
          aws ecs describe-task-definition --task-definition "$TASK_DEF" --query 'taskDefinition.family' || true

      - name: Download task definition
        run: |
          TASK_DEF="${{ steps.get-task-info.outputs.task_def }}"
          
          # If this fails due to task definition not existing, try alternative approaches
          if ! aws ecs describe-task-definition --task-definition "$TASK_DEF" --query taskDefinition > task-definition.json 2>/dev/null; then
            echo "Task definition $TASK_DEF not found, trying alternative approaches"
            
            # For id-trading-like rules, try just 'id-trading'
            if [[ "${{ matrix.task }}" == "id-trading"* ]]; then
              echo "Trying 'id-trading'"
              if aws ecs describe-task-definition --task-definition "id-trading" --query taskDefinition > task-definition.json 2>/dev/null; then
                echo "Found task definition 'id-trading'"
                TASK_DEF="id-trading"
              else
                echo "Task definition 'id-trading' not found"
              fi
            fi
            
            # For imbalance-price-cz-like rules, try just 'imbalance-price-cz'
            if [[ "${{ matrix.task }}" == "imbalance-price-cz"* ]]; then
              echo "Trying 'imbalance-price-cz'"
              if aws ecs describe-task-definition --task-definition "imbalance-price-cz" --query taskDefinition > task-definition.json 2>/dev/null; then
                echo "Found task definition 'imbalance-price-cz'"
                TASK_DEF="imbalance-price-cz"
              else
                echo "Task definition 'imbalance-price-cz' not found"
              fi
            fi
            
            # List all task definitions that might be related
            echo "All task definitions that might be related:"
            for prefix in $(echo "${{ matrix.task }}" | tr '-' '\n' | head -n 2); do
              echo "Checking prefix: $prefix"
              aws ecs list-task-definitions --family-prefix "$prefix" --status ACTIVE
            done
            
            # If all else fails, exit with error
            if [ ! -f task-definition.json ]; then
              echo "Task definition not found with any known pattern, cannot proceed"
              exit 1
            fi
          fi
          
          echo "Downloaded task definition for $TASK_DEF"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.2.0
        with:
          task-definition: task-definition.json
          container-name: main
          image: ${{ inputs.image }}

      - name: Prepare new task definition
        run: |
          cat ${{ steps.render-task-def.outputs.task-definition }} | jq 'del(.taskDefinitionArn) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.revision) | del(.registeredAt) | del(.registeredBy)' > task-definition-ready.json

      - name: Register the new task definition
        run: |
          aws ecs register-task-definition --cli-input-json file://task-definition-ready.json > task-definition-registered.json
          NEW_TASK_ARN=$(jq -r '.taskDefinition.taskDefinitionArn' task-definition-registered.json)
          echo "new_task_arn=$NEW_TASK_ARN" >> $GITHUB_ENV

      - name: Update EventBridge Rule
        if: steps.get-task-info.outputs.task_type == 'rule'
        run: |
          aws events list-targets-by-rule --rule ${{ matrix.task }} > rule-target.json
          echo "Current target configuration:"
          cat rule-target.json
          
          jq --arg new_task_arn "${{ env.new_task_arn }}" '.Targets[].EcsParameters.TaskDefinitionArn = $new_task_arn' rule-target.json > new-target.json
          
          echo "New target configuration:"
          cat new-target.json
          
          TARGETS=$(jq -c '.Targets' new-target.json)
          aws events put-targets --rule ${{ matrix.task }} --targets "$TARGETS"

      - name: Update EventBridge Scheduler
        if: steps.get-task-info.outputs.task_type == 'schedule'
        run: |
          aws scheduler get-schedule --name "${{ matrix.task }}" > schedule.json
          echo "Current schedule configuration:"
          cat schedule.json
          
          # Create updated target with new task definition ARN
          jq --arg new_task_arn "${{ env.new_task_arn }}" '.Target.EcsParameters.TaskDefinitionArn = $new_task_arn' schedule.json > updated-target.json
          TARGET=$(jq -c '.Target' updated-target.json)
          
          # Get other required parameters
          SCHEDULE_EXPRESSION=$(jq -r '.ScheduleExpression' schedule.json)
          FLEX_TIME_WINDOW=$(jq -c '.FlexibleTimeWindow' schedule.json)
          
          # Update the schedule
          aws scheduler update-schedule \
            --name "${{ matrix.task }}" \
            --schedule-expression "$SCHEDULE_EXPRESSION" \
            --flexible-time-window "$FLEX_TIME_WINDOW" \
            --target "$TARGET"
