on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
        description: "set this to AWS_ACCESS_KEY_ID of your user"
      aws-secret-access-key:
        required: true
        description: "set this to AWS_SECRET_ACCESS_KEY of your user"

    inputs:
      aws-region:
        required: true
        type: string
        description: "set this to your preferred AWS region, e.g. us-west-1"
      instance:
        required: true
        type: string
        description: "set this to your instance name - service/task definition name, e.g. emsi-stm-dubnica"

    # TODO
    outputs:
      tag-to-deploy:
        description: "Published image tag for immediate deployment"
        value: ${{ jobs.common-java-app-build.outputs.tag-to-deploy }}

jobs:
  list-instances:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      instances-matrix: ${{ steps.get-all-instances.outputs.instances-matrix }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
          mask-aws-account-id: true

      - name: Get all instances for app
        id: get-all-instances
        run: |
          # get all requested task definitions
          defs=$(aws ecs list-task-definitions --region eu-central-1 | grep r-api-wrapper | rev | cut -d "/" -f 1 | rev | cut -d ":" -f 1 | uniq)

          echo "all listed services/task defs:"
          echo "${defs}"

          matrix_json_definition="{ \"instance\" : [ "

          # add instances
          for def in ${defs}
          do
            echo "def: ${def} - adding to matrix"

            matrix_json_definition+="\"${def}\","
          done

          # finish end of the json
          matrix_json_definition=${matrix_json_definition::-1}
          matrix_json_definition="${matrix_json_definition} ] }"

          echo "final json matrix definition: '${matrix_json_definition}'"

          echo "instances-matrix=$( echo  ${matrix_json_definition})" >> "$GITHUB_OUTPUT"

          echo "### \#\# going to deploy following services: ${defs}" >> $GITHUB_STEP_SUMMARY
